### ISSUE TITLE
Error NameError: name 'multithreaded' is not defined (no output)

### ISSUE THREAD

**Issue by vkartha** [douglasyao/FR-Perturb#3]
Hey @douglasyao ! I was able to clone the environment, and load up the data OK, FR-perturb code seemed to be running fine (including the permutation steps), but it errors out right after logging the time, and I don't get any output files to inspect. Standard out (including error at end) shown below:

```

Loading input data...
Done
Regressing out covariates and centering expression matrix...
Done
Factorizing expression matrix...
Done
Regressing left factor matrix on perturbation design matrix...
Done
Computing p-values by permutation testing (500 total permutations)...
100%|████████████████████████████████████████████████████████████████████| 500/500 [00:10<00:00, 46.64it/s]
Fitting skew-normal distribution to effects with p=0 (125799 total effects)...
Analysis finished at Wed Mar 29 23:33:06 2023
Total time elapsed: 1.0m:48.97s
Traceback (most recent call last):
  File "./run_FR_Perturb.py", line 331, in <module>
    if multithreaded:
NameError: name 'multithreaded' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run_FR_Perturb.py", line 365, in <module>
    log.log(traceback.format_exc(ex))
  File "/home/vinay/anaconda3/envs/FR-Perturb/lib/python3.8/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/home/vinay/anaconda3/envs/FR-Perturb/lib/python3.8/traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "/home/vinay/anaconda3/envs/FR-Perturb/lib/python3.8/traceback.py", line 508, in __init__
    self.stack = StackSummary.extract(
  File "/home/vinay/anaconda3/envs/FR-Perturb/lib/python3.8/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'NameError' and 'int'

```
The error occurs whether I specify the --multithreaded param or not. 

Any help would be appreciated!

**Comment by vkartha** [comment]
I'm assuming this line (331 in run_FR_Perturb.py) is the culprit:

```
  if multithreaded:
                    fitted_pvals = thread_map(lambda i: fit_skew_norm(B_flattened[i], B_perms[i,:]), zero_indices) 
```

**Comment by vkartha** [comment]
I edited the python script by changing `if multithreaded` above to `if arg.multithreaded` and that seemed to then allow the fitted pval calculation to run, but unfortunately I hit a different error once that was over, possibly related to writing the output?:

```
Loading input data...
Done
Regressing out covariates and centering expression matrix...
Done
Factorizing expression matrix...
Done
Regressing left factor matrix on perturbation design matrix...
Done
Computing p-values by permutation testing (500 total permutations)...
100%|████████████████████████████████████████████████████████████████████| 500/500 [00:11<00:00, 44.09it/s]
Fitting skew-normal distribution to effects with p=0 (128070 total effects)...
100%|████████████████████████████████████████████████████████████| 128070/128070 [1:08:11<00:00, 31.30it/s]
Done
Analysis finished at Thu Mar 30 01:37:03 2023
Total time elapsed: 1.0h:12.0m:26.23999999999978s
Traceback (most recent call last):
  File "./run_FR_Perturb.py", line 347, in <module>
    pvals = pd.DataFrame(data = np.transpose(pvals), index = dat.var.features, columns = p_mat_pd.index)
  File "/home/vinay/anaconda3/envs/FR-Perturb/lib/python3.8/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'features'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run_FR_Perturb.py", line 365, in <module>
    log.log(traceback.format_exc(ex))
  File "/home/vinay/anaconda3/envs/FR-Perturb/lib/python3.8/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/home/vinay/anaconda3/envs/FR-Perturb/lib/python3.8/traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "/home/vinay/anaconda3/envs/FR-Perturb/lib/python3.8/traceback.py", line 508, in __init__
    self.stack = StackSummary.extract(
  File "/home/vinay/anaconda3/envs/FR-Perturb/lib/python3.8/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'AttributeError' and 'int'

```

**Comment by douglasyao** [comment]
Should be fixed now! Sorry it took so long.
