### ISSUE TITLE
Guide pool 

### ISSUE THREAD

**Issue by jr-ran** [douglasyao/FR-Perturb#4]
For the guide-pooled screen,article focused on the 8,448 cells with 3 or more guides.  When I was follow ,there are some issue. effect size is NaN or 0.

[/nis_home/FR-Perturb/bin/python /locald/FR-Perturb/run_FR_Perturb.py \
 --input-h5ad /path/GSM6858450_KD_guide_pooled.h5ad \
 --input-perturbation-matrix /path/GSM6858450_KD_guide_pooled_perturbations.txt \
 --control-perturbation-name non-targeting,safe-targeting \
 --covariates Total_RNA_count,Percent_mitochondrial_reads,Cell_cycle_phase \
 --compute-pval --fit-zero-pval --multithreaded \
 --guide-pooled \
 --out GSM6858450_KD_guide_pooled](url)

[Traceback (most recent call last):
  File "/path/FR-Perturb/run_FR_Perturb.py", line 350, in <module>
    fitted_pvals = thread_map(lambda i: fit_skew_norm(B_flattened[i], B_perms[i,:]), zero_indices)
  File "/nis_home/user/crispr/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 94, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/nis_home/user/crispr/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "/nis_home/user/crispr/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/nis_home/user/crispr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/nis_home/user/crispr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/nis_home/user/crispr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/nis_home/user/crispr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/path/FR-Perturb/run_FR_Perturb.py", line 350, in <lambda>
    fitted_pvals = thread_map(lambda i: fit_skew_norm(B_flattened[i], B_perms[i,:]), zero_indices)
  File "/path/FR-Perturb/run_FR_Perturb.py", line 81, in fit_skew_norm
    fit = scipy.stats.skewnorm.fit(t_nulls)
  File "/nis_home/user/crispr/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py", line 2473, in fit
    raise RuntimeError("The data contains non-finite values.")
RuntimeError: The data contains non-finite values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/FR-Perturb/run_FR_Perturb.py", line 383, in <module>
    log.log(traceback.format_exc(ex))
  File "/nis_home/user/crispr/lib/python3.8/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/nis_home/user/crispr/lib/python3.8/traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "/nis_home/user/crispr/lib/python3.8/traceback.py", line 508, in __init__
    self.stack = StackSummary.extract(
  File "/nis_home/user/crispr/lib/python3.8/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'RuntimeError' and 'int'](url)

**Comment by douglasyao** [comment]
Hi,

Can you make sure that you're using the most recent version of FR-Perturb?
Also, can you make sure that you run "conda activate FR-Perturb" before
running the code? It seems like the version of python being used does not
match the environment.

-Doug
